# Generated by Django 4.0.5 on 2022-07-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_alter_room_options_remove_room_uptated_room_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='about', verbose_name='Imagen')),
                ('image_security', models.ImageField(upload_to='about', verbose_name='Imagen de Seguridad')),
                ('description_security', models.TextField(verbose_name='Descripcion de Seguridad')),
                ('image_price', models.ImageField(upload_to='about', verbose_name='Imagen de Precio')),
                ('description_price', models.TextField(verbose_name='Descripcion de Precio')),
                ('image_availability', models.ImageField(upload_to='about', verbose_name='Imagen de Disponibilidad')),
                ('description_availability', models.TextField(verbose_name='Descripcion de Disponibilidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
            ],
            options={
                'verbose_name': 'Nosotro',
                'verbose_name_plural': 'Nosotros',
                'ordering': ['-created'],
            },
        ),
    ]
